version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: book_store
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mysql:/var/lib/mysql